In [177]:
import pandas as pd 
import solid 
from urllib import urlencode
from math import *

In [3]:
data = pd.read_csv('https://data.cityofchicago.org/api/views/9m5u-3f29/rows.csv?accessType=DOWNLOAD')

In [26]:
data.describe()

,Average Days to Complete Graffiti Removal,Total Completed Requests,Median Days to Complete Graffiti Removal Request,Target Response Time (Days)
count,28.000000,28.000000,27.000000,2
mean,7.456429,2099.785714,2.962963,10
std,2.088088,340.938830,1.192331,0
min,3.100000,1430.000000,1.000000,10
25%,6.047500,1927.500000,2.000000,10
50%,7.325000,2160.000000,3.000000,10
75%,9.175000,2309.000000,4.000000,10
max,11.570000,2706.000000,5.000000,10

In [14]:
polygon =solid.polygon(([1,2],[2,3],[1,3],[2,2]))

In [20]:
from solid.utils import *
extrude_along_path

In [21]:
def path():
    return [Point3(0,0,0), Point3(0,0,1)]

In [24]:
shape =extrude_along_path(shape_pts=[Point3(1,2,0),Point3(2,3,0),Point3(1,3,0),Point3(2,2,0)], path_pts=path())

polyhedron(points = [[0.0000000000, 0.0000000000, 0.0000000000], [0.0000000000, 0.0000000000, 0.0000000000], [0.0000000000, 0.0000000000, 0.0000000000], [0.0000000000, 0.0000000000, 0.0000000000], [0.0000000000, 0.0000000000, 1.0000000000], [0.0000000000, 0.0000000000, 1.0000000000], [0.0000000000, 0.0000000000, 1.0000000000], [0.0000000000, 0.0000000000, 1.0000000000]], triangles = [[0, 4, 1], [1, 4, 5], [1, 5, 2], [2, 5, 6], [2, 6, 3], [3, 6, 7], [0, 3, 7], [0, 7, 4], [0, 1, 2], [0, 2, 3], [4, 6, 5], [4, 7, 6]]);

In [16]:
from solid import *
d = difference()(
    cube(10),
    sphere(15)
)
print(scad_render(d))

difference() {
	cube(size = 10);
	sphere(r = 15);
}

## Get data

In [99]:
a = []
for i in range(1,13):
    monthly = pd.read_csv('https://www.ncdc.noaa.gov/cag/time-series/global/globe/land_ocean/1/{0}/1880-2015.csv'.format(i), header=3)
    monthly['month'] = i
    a.append(monthly)
total = pd.concat(a)

In [206]:
def angle(month, total_segments):
    return (month/float(total_segments))*2*pi

In [236]:
def radius(data,max=10,min=1):
    return (data - min_val)*(max-min)/(max_val-min_val) + min

In [208]:
max_val, min_val = total['Value'].max(), total['Value'].min()
segment_height = 2

In [ ]:
def segment_path( values, segments, height= 20, max_r, min_r):
    shape = [[radius(d,max_r,min_r)*sin(angle(segment-1,len(segments))), radius(d,max_r,min_r)*cos(angle(segment-1,len(segments)))] for segment,d in zip(segments, values)]
    return linear_extrude(height=height)(polygon(points=shape))

In [237]:
def make_sculpture(data, vertical_col, segment_col, value_col,segment_height=2):
    segments = []
    for offset, vCol  in enumerate(range(data[vertical_col].min(), data[vertical_col].max())):
        print offset,vCol
        section_data = data[data[vertical_col]==vCol].sort(columns=segment_col, ascending=True)
        segments.append(up(segment_height*offset)(segment_path(section_data[value_col], section_data[segment_col],height=segment_height)))
    final = union()(segments)
    return final

In [ ]:
final = make_sculpture(total, "Year", 'month', 'Value')

In [ ]:
with open('sculpture.scad', 'w') as f:
    f.write(scad_render(final).replace('triangles','faces'))

In [ ]:
total['Year'].max()

# Chicago Crime Data

In [ ]:
query= {'q':'''
    select week,year,primary_type, count from crimes_2001_to_present_summary
''', 'format':'csv'}

crimes = pd.read_csv('https://stuartlynn.cartodb.com/api/v2/sql?'+urlencode(query))

In [238]:
for crime in crimes['primary_type'].unique():
    print 'doing :', crime
    data = crimes[crimes['primary_type']==crime]
    sculpt = make_sculpture(data, 'year', 'week','count',segment_height=20)
    with open('chicago_crimes/{0}.scad'.format(crime), 'w') as f:
        f.write(scad_render(sculpt).replace('triangles','faces'))

doing : ARSON
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : ASSAULT
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : BATTERY
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : BURGLARY
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : CRIMINAL DAMAGE
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : CRIMINAL TRESPASS
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : CRIM SEXUAL ASSAULT
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : DECEPTIVE PRACTICE
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : GAMBLING
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : HOMICIDE
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : INTERFERENCE WITH PUBLIC OFFICER
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : INTIMIDATION
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : KIDNAPPING
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : LIQUOR LAW VIOLATION
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : MOTOR VEHICLE THEFT
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : NARCOTICS
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : OFFENSE INVOLVING CHILDREN
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : OTHER OFFENSE
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : PROSTITUTION
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : PUBLIC PEACE VIOLATION
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : RITUALISM
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
doing : ROBBERY
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : SEX OFFENSE
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : STALKING
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : THEFT
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : WEAPONS VIOLATION
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : OBSCENITY
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : OTHER NARCOTIC VIOLATION
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : PUBLIC INDECENCY
0 2001
1 2002
2 2003
3 2004
4 2005
5 2006
6 2007
7 2008
8 2009
9 2010
10 2011
11 2012
12 2013
13 2014
14 2015
doing : HUMAN TRAFFICKING
0 2014
1 2015
doing : NON-CRIMINAL (SUBJECT SPECIFIED)
0 2012
1 2013
2 2014
3 2015
doing : DOMESTIC VIOLENCE
doing : NON - CRIMINAL
0 2013
1 2014
2 2015
doing : CONCEALED CARRY LICENSE VIOLATION
0 2014
1 2015
doing : NON-CRIMINAL
0 2012
1 2013
2 2014
3 2015

In [218]:
data['year']

0        2001
26       2002
50       2003
76       2004
101      2005
126      2006
152      2007
178      2008
203      2009
228      2010
253      2011
278      2012
305      2013
330      2014
354      2015
379      2016
403      2001
431      2002
457      2003
482      2004
509      2005
534      2006
560      2007
585      2008
611      2009
636      2010
662      2011
688      2012
714      2013
738      2014
         ...
19831    2007
19856    2008
19881    2009
19907    2010
19933    2011
19958    2012
19982    2013
20008    2014
20034    2015
20058    2001
20083    2002
20108    2003
20133    2004
20159    2005
20184    2006
20211    2007
20236    2008
20260    2009
20285    2010
20311    2011
20336    2012
20361    2013
20385    2014
20412    2015
20437    2004
20462    2005
20485    2009
20509    2010
20534    2015
20558    2016
Name: year, dtype: int64